### ISSUE TITLE
HTML colour clash

### ISSUE THREAD

**Issue by djch** [emlai/civic-syntax#1]
First of all, this is a great colour scheme (thanks Apple) and well ported (thanks @emlai).

The only place it's a little rough for me—in the Django projects I work on—is HTML templates where the red is a little bit too predominant, in my opinion.

Having, for example, attribute values be the same colour as their tags makes things a little hard to scan. For all I know this is exactly how it is in Xcode, and might be necessary, but I thought I'd put it out there in case it can be improved.

Thanks!

***

![civic](https://cloud.githubusercontent.com/assets/4392286/16170467/05d3dc40-3597-11e6-9201-166b9a9e213c.png)
![one-dark](https://cloud.githubusercontent.com/assets/4392286/16170469/062259ba-3597-11e6-9bca-e0b4ad3df8fc.png)

**Comment by emlai** [comment]
Thanks! I haven't tested this out with HTML yet, glad you did! I'll try to fix this in a while.

**Comment by emlai** [comment]
Here's what it looks like now:

<img width="798" alt="screen shot 2016-06-18 at 14 52 13" src="https://cloud.githubusercontent.com/assets/7543552/16170678/65d8ea14-3564-11e6-8b09-0716c3318f60.png">
