### ISSUE TITLE
Color clash in HTML

### ISSUE THREAD

**Issue by matthewpeixoto** [emlai/civic-syntax#3]
<img width="371" alt="screen shot 2016-10-29 at 10 35 59 am" src="https://cloud.githubusercontent.com/assets/16690200/19830327/90113652-9dc3-11e6-8de1-e692bcafe82d.png">

Element content is hard to locate because it is the same color as the ID attribute value and bracket characters.

**Comment by emlai** [comment]
Thanks!

I'm thinking of changing the ID attribute value color to red. What do you think?

**Comment by matthewpeixoto** [comment]
That might work well!

I'm personally not a big fan of how the red looks on such a dark background so I'm finding a setup like this usable for my needs. Feel free to take inspiration from it!

![screen shot 2016-10-29 at 7 21 19 pm](https://cloud.githubusercontent.com/assets/16690200/19833374/5492330c-9e0d-11e6-8d97-157f86c8d827.png)

**Comment by emlai** [comment]
That looks cool 👍, but OTOH the original Xcode theme maps magenta to keywords, and red to strings, and I'd like to keep it as close to that as possible. (I think using magenta for HTML tags and red for HTML attribute values is pretty close.)

> I'm personally not a big fan of how the red looks on such a dark background

Me neither. I'll see if making it a little brighter would help.

**Comment by emlai** [comment]
Fixed these issues in v0.2.3.

**Comment by matthewpeixoto** [comment]
Looks great, thank you!

Did you make the red brighter? It seems much more vivid than the rest of the colours. In this case, it might just be better to use the exact red from Xcode.
